/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Were_Wolf_Display;

/**
 *
 * @author COMPUTER
 */
public class Create_Room extends javax.swing.JPanel {

    /**
     * Creates new form Create_Room
     */
    public Create_Room() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(60, 170, 22, 22);

        jButton2.setText("+");
        add(jButton2);
        jButton2.setBounds(130, 170, 22, 22);

        jLabel12.setText("Số");
        add(jLabel12);
        jLabel12.setBounds(400, 350, 17, 16);

        jButton21.setText("Thoát Phòng");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        add(jButton21);
        jButton21.setBounds(10, 10, 110, 30);

        jButton22.setText("Tạo phòng");
        add(jButton22);
        jButton22.setBounds(610, 380, 190, 70);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_villager_filled.png")); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel13);
        jLabel13.setBounds(50, 50, 110, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_fool_filled.png")); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5);
        jLabel5.setBounds(50, 200, 110, 110);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_gunner_filled.png")); // NOI18N
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel18);
        jLabel18.setBounds(50, 350, 110, 110);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_spirit_seer_filled.png")); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel23);
        jLabel23.setBounds(180, 350, 110, 110);

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_cursed_human_filled.png")); // NOI18N
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel24);
        jLabel24.setBounds(310, 350, 110, 110);

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_seer_filled.png")); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel25);
        jLabel25.setBounds(180, 200, 110, 110);

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_medium_filled.png")); // NOI18N
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel26);
        jLabel26.setBounds(310, 200, 110, 110);

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_doctor_filled.png")); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel27);
        jLabel27.setBounds(180, 50, 110, 110);

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_werewolf_filled.png")); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel28);
        jLabel28.setBounds(310, 50, 110, 110);

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\res\\res\\drawable-mdpi-v4\\icon_wolf_seer_filled.png")); // NOI18N
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel29);
        jLabel29.setBounds(440, 50, 110, 110);

        jButton3.setText("+");
        add(jButton3);
        jButton3.setBounds(260, 170, 22, 22);

        jButton4.setText("-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(190, 170, 22, 22);

        jButton5.setText("+");
        add(jButton5);
        jButton5.setBounds(390, 170, 22, 22);

        jButton6.setText("-");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(320, 170, 22, 22);

        jButton7.setText("+");
        add(jButton7);
        jButton7.setBounds(520, 170, 22, 22);

        jButton8.setText("-");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);
        jButton8.setBounds(450, 170, 22, 22);

        jButton9.setText("+");
        add(jButton9);
        jButton9.setBounds(130, 320, 22, 22);

        jButton10.setText("-");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10);
        jButton10.setBounds(60, 320, 22, 22);

        jButton11.setText("+");
        add(jButton11);
        jButton11.setBounds(260, 320, 22, 22);

        jButton12.setText("-");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12);
        jButton12.setBounds(190, 320, 22, 22);

        jButton13.setText("+");
        add(jButton13);
        jButton13.setBounds(390, 320, 22, 22);

        jButton14.setText("-");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        add(jButton14);
        jButton14.setBounds(320, 320, 22, 22);

        jButton15.setText("+");
        add(jButton15);
        jButton15.setBounds(130, 470, 22, 22);

        jButton16.setText("-");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        add(jButton16);
        jButton16.setBounds(60, 470, 22, 22);

        jButton17.setText("+");
        add(jButton17);
        jButton17.setBounds(260, 470, 22, 22);

        jButton18.setText("-");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        add(jButton18);
        jButton18.setBounds(190, 470, 22, 22);

        jButton19.setText("-");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        add(jButton19);
        jButton19.setBounds(320, 470, 22, 22);

        jButton20.setText("+");
        add(jButton20);
        jButton20.setBounds(390, 470, 22, 22);

        jLabel14.setText("Số");
        add(jLabel14);
        jLabel14.setBounds(140, 50, 17, 16);

        jLabel15.setText("Số");
        add(jLabel15);
        jLabel15.setBounds(270, 50, 17, 16);

        jLabel16.setText("Số");
        add(jLabel16);
        jLabel16.setBounds(400, 50, 17, 16);

        jLabel17.setText("Số");
        add(jLabel17);
        jLabel17.setBounds(530, 50, 17, 16);

        jLabel19.setText("Số");
        add(jLabel19);
        jLabel19.setBounds(140, 200, 17, 16);

        jLabel20.setText("Số");
        add(jLabel20);
        jLabel20.setBounds(270, 200, 17, 16);

        jLabel21.setText("Số");
        add(jLabel21);
        jLabel21.setBounds(400, 200, 17, 16);

        jLabel22.setText("Số");
        add(jLabel22);
        jLabel22.setBounds(140, 350, 17, 16);

        jLabel30.setText("Số");
        add(jLabel30);
        jLabel30.setBounds(270, 350, 17, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/assets_images_moon.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(610, -230, 550, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
