/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Were_Wolf_Display;

/**
 *
 * @author COMPUTER
 */
public class Create_Room extends javax.swing.JPanel {

    /**
     * Creates new form Create_Room
     */
    public Create_Room() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();

        setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\THAY_DONG_ROLE.png")); // NOI18N
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel7);
        jLabel7.setBounds(294, 210, 100, 96);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\role1.png")); // NOI18N
        jLabel8.setText("jLabel2");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel8);
        jLabel8.setBounds(294, 347, 100, 101);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\soi.png")); // NOI18N
        jLabel9.setText("jLabel2");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel9);
        jLabel9.setBounds(294, 51, 100, 113);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\xathu.png")); // NOI18N
        jLabel10.setText("jLabel2");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel10);
        jLabel10.setBounds(169, 347, 100, 101);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\baove.png")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel2);
        jLabel2.setBounds(169, 51, 100, 113);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\soitri.png")); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel3);
        jLabel3.setBounds(51, 210, 100, 96);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\thanghe.png")); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel4);
        jLabel4.setBounds(169, 210, 100, 96);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\dan.png")); // NOI18N
        jLabel5.setText("jLabel2");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel5);
        jLabel5.setBounds(51, 51, 100, 113);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\tientri.png")); // NOI18N
        jLabel6.setText("jLabel2");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel6);
        jLabel6.setBounds(51, 347, 100, 101);

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(51, 170, 22, 22);

        jButton2.setText("+");
        add(jButton2);
        jButton2.setBounds(129, 170, 22, 22);

        jButton3.setText("-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(169, 170, 22, 22);

        jButton4.setText("+");
        add(jButton4);
        jButton4.setBounds(247, 170, 22, 22);

        jButton5.setText("-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(294, 170, 22, 22);

        jButton6.setText("+");
        add(jButton6);
        jButton6.setBounds(372, 170, 22, 22);

        jButton7.setText("-");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(51, 312, 22, 22);

        jButton8.setText("+");
        add(jButton8);
        jButton8.setBounds(129, 312, 22, 22);

        jButton9.setText("-");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9);
        jButton9.setBounds(169, 312, 22, 22);

        jButton10.setText("+");
        add(jButton10);
        jButton10.setBounds(247, 312, 22, 22);

        jButton11.setText("-");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11);
        jButton11.setBounds(294, 312, 22, 22);

        jButton12.setText("+");
        add(jButton12);
        jButton12.setBounds(372, 312, 22, 22);

        jButton13.setText("-");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        add(jButton13);
        jButton13.setBounds(51, 454, 22, 22);

        jButton14.setText("+");
        add(jButton14);
        jButton14.setBounds(129, 454, 22, 22);

        jButton15.setText("-");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        add(jButton15);
        jButton15.setBounds(169, 454, 22, 22);

        jButton16.setText("+");
        add(jButton16);
        jButton16.setBounds(247, 454, 22, 22);

        jButton17.setText("-");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        add(jButton17);
        jButton17.setBounds(294, 454, 22, 22);

        jButton18.setText("+");
        add(jButton18);
        jButton18.setBounds(372, 454, 22, 22);

        jLabel1.setText("Số");
        add(jLabel1);
        jLabel1.setBounds(250, 350, 17, 16);

        jLabel11.setText("Số");
        add(jLabel11);
        jLabel11.setBounds(250, 50, 17, 16);

        jLabel12.setText("Số");
        add(jLabel12);
        jLabel12.setBounds(130, 50, 17, 16);

        jLabel13.setText("Số");
        add(jLabel13);
        jLabel13.setBounds(250, 210, 17, 16);

        jLabel14.setText("Số");
        add(jLabel14);
        jLabel14.setBounds(130, 210, 17, 16);

        jLabel15.setText("Số");
        add(jLabel15);
        jLabel15.setBounds(370, 50, 17, 16);

        jLabel17.setText("Số");
        add(jLabel17);
        jLabel17.setBounds(130, 350, 17, 16);

        jLabel18.setText("Số");
        add(jLabel18);
        jLabel18.setBounds(370, 210, 17, 16);

        jLabel19.setText("Số");
        add(jLabel19);
        jLabel19.setBounds(370, 350, 17, 16);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\laynhiem.png")); // NOI18N
        jLabel20.setText("jLabel2");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jLabel20);
        jLabel20.setBounds(420, 50, 110, 113);

        jButton19.setText("-");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        add(jButton19);
        jButton19.setBounds(420, 170, 22, 22);

        jButton20.setText("+");
        add(jButton20);
        jButton20.setBounds(510, 170, 22, 22);

        jLabel21.setText("Số");
        add(jLabel21);
        jLabel21.setBounds(510, 50, 17, 16);

        jButton21.setText("Thoát Phòng");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        add(jButton21);
        jButton21.setBounds(10, 10, 110, 30);

        jButton22.setText("Tạo phòng");
        add(jButton22);
        jButton22.setBounds(610, 380, 190, 70);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton21ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
