/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Were_Wolf_Display;

/**
 *
 * @author COMPUTER
 */
public class Waiting_room extends javax.swing.JPanel {

    /**
     * Creates new form Waiting_room
     */
    public Waiting_room() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(860, 502));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\aaaaa.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(148, 73, 102, 79);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 208, 100, 101);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(156, 208, 100, 101);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\sasuke.jpg")); // NOI18N
        jLabel5.setText("jLabel2");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 73, 100, 94);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 342, 100, 101);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel7.setText("jLabel2");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(268, 208, 100, 101);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel8.setText("jLabel2");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(268, 342, 100, 101);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel9.setText("jLabel2");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(268, 73, 100, 101);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel10.setText("jLabel2");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 342, 100, 101);

        jLabel1.setText("Chủ phòng");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 48, 60, 16);

        jButton1.setText("Thoát phòng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(6, 6, 120, 32);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(401, 73, 455, 280);

        jTextField1.setText("Chat here");
        jPanel1.add(jTextField1);
        jTextField1.setBounds(401, 371, 337, 59);

        jButton2.setText("Gửi");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(744, 371, 112, 59);

        jLabel11.setText("Tên");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(30, 180, 19, 16);

        jLabel12.setText("Tên");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(148, 180, 19, 16);

        jLabel13.setText("Tên");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(262, 180, 19, 16);

        jLabel14.setText("Tên");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 312, 19, 24);

        jLabel15.setText("Tên");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(150, 312, 19, 24);

        jLabel16.setText("Tên");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(268, 312, 19, 24);

        jLabel17.setText("Tên");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(30, 449, 19, 24);

        jLabel18.setText("Tên");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(150, 449, 19, 24);

        jLabel19.setText("Tên");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(268, 449, 19, 24);
        jPanel1.add(jLabel20);
        jLabel20.setBounds(385, 30, 0, 0);

        jLabel22.setText("role");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(109, 180, 20, 16);

        jLabel23.setText("role");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(235, 180, 20, 16);

        jLabel24.setText("role");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(347, 180, 20, 16);

        jLabel25.setText("role");
        jPanel1.add(jLabel25);
        jLabel25.setBounds(347, 316, 20, 16);

        jLabel26.setText("role");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(109, 316, 20, 16);

        jLabel27.setText("role");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(229, 316, 20, 16);

        jLabel28.setText("role");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(347, 453, 20, 16);

        jLabel29.setText("role");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(109, 453, 20, 16);

        jLabel30.setText("role");
        jPanel1.add(jLabel30);
        jLabel30.setBounds(229, 453, 20, 16);

        jButton3.setText("Bắt Đầu");
        jPanel1.add(jButton3);
        jButton3.setBounds(673, 449, 165, 53);

        jButton4.setText("Chỉnh sửa role");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(401, 450, 138, 52);

        jLabel21.setText("Sói");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(233, 7, 16, 16);

        jLabel31.setText("Dân làng");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(303, 7, 47, 16);

        jLabel32.setText("Bảo vệ");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(385, 7, 35, 16);

        jLabel33.setText("Tiên Tri");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(498, 8, 38, 16);

        jLabel34.setText("Kẻ lây nhiễm");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(577, 7, 68, 16);

        jLabel35.setText("Sói Tri");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(233, 37, 32, 16);

        jLabel36.setText("Xạ thủ");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(303, 37, 34, 16);

        jLabel37.setText("Thầy Đồng");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(385, 37, 57, 16);

        jLabel38.setText("Thằng hề");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(498, 37, 49, 16);

        jLabel39.setText("Role 10");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(577, 37, 38, 16);

        jLabel40.setText("0");
        jLabel40.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel40);
        jLabel40.setBounds(209, 6, 18, 18);

        jLabel41.setText("0");
        jLabel41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel41);
        jLabel41.setBounds(209, 36, 18, 18);

        jLabel42.setText("0");
        jLabel42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel42);
        jLabel42.setBounds(279, 6, 18, 18);

        jLabel43.setText("0");
        jLabel43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel43);
        jLabel43.setBounds(279, 36, 18, 18);

        jLabel44.setText("0");
        jLabel44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel44);
        jLabel44.setBounds(363, 6, 18, 18);

        jLabel45.setText("0");
        jLabel45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel45);
        jLabel45.setBounds(361, 36, 18, 18);

        jLabel46.setText("0");
        jLabel46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel46);
        jLabel46.setBounds(479, 6, 18, 18);

        jLabel47.setText("0");
        jLabel47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel47);
        jLabel47.setBounds(479, 36, 18, 18);

        jLabel48.setText("0");
        jLabel48.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel48);
        jLabel48.setBounds(553, 6, 18, 18);

        jLabel49.setText("0");
        jLabel49.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel1.add(jLabel49);
        jLabel49.setBounds(553, 36, 18, 18);

        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(860, 502));
        jPanel2.setLayout(null);

        jLabel50.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\aaaaa.jpg")); // NOI18N
        jPanel2.add(jLabel50);
        jLabel50.setBounds(148, 73, 102, 79);

        jLabel51.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel51.setText("jLabel2");
        jPanel2.add(jLabel51);
        jLabel51.setBounds(30, 208, 100, 101);

        jLabel52.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel52.setText("jLabel2");
        jPanel2.add(jLabel52);
        jLabel52.setBounds(156, 208, 100, 101);

        jLabel53.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\sasuke.jpg")); // NOI18N
        jLabel53.setText("jLabel2");
        jPanel2.add(jLabel53);
        jLabel53.setBounds(30, 73, 100, 94);

        jLabel54.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel54.setText("jLabel2");
        jPanel2.add(jLabel54);
        jLabel54.setBounds(30, 342, 100, 101);

        jLabel55.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel55.setText("jLabel2");
        jPanel2.add(jLabel55);
        jLabel55.setBounds(268, 208, 100, 101);

        jLabel56.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel56.setText("jLabel2");
        jPanel2.add(jLabel56);
        jLabel56.setBounds(268, 342, 100, 101);

        jLabel57.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel57.setText("jLabel2");
        jPanel2.add(jLabel57);
        jLabel57.setBounds(268, 73, 100, 101);

        jLabel58.setIcon(new javax.swing.ImageIcon("C:\\Users\\COMPUTER\\Downloads\\assets\\assets\\ava4.jpg")); // NOI18N
        jLabel58.setText("jLabel2");
        jPanel2.add(jLabel58);
        jLabel58.setBounds(150, 342, 100, 101);

        jLabel59.setText("Chủ phòng");
        jPanel2.add(jLabel59);
        jLabel59.setBounds(30, 48, 60, 16);

        jButton5.setText("Thoát phòng");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(6, 6, 120, 32);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(401, 73, 455, 280);

        jTextField2.setText("Chat here");
        jPanel2.add(jTextField2);
        jTextField2.setBounds(401, 371, 337, 59);

        jButton6.setText("Gửi");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(744, 371, 112, 59);

        jLabel60.setText("Tên");
        jPanel2.add(jLabel60);
        jLabel60.setBounds(30, 180, 19, 16);

        jLabel61.setText("Tên");
        jPanel2.add(jLabel61);
        jLabel61.setBounds(148, 180, 19, 16);

        jLabel62.setText("Tên");
        jPanel2.add(jLabel62);
        jLabel62.setBounds(262, 180, 19, 16);

        jLabel63.setText("Tên");
        jPanel2.add(jLabel63);
        jLabel63.setBounds(30, 312, 19, 24);

        jLabel64.setText("Tên");
        jPanel2.add(jLabel64);
        jLabel64.setBounds(150, 312, 19, 24);

        jLabel65.setText("Tên");
        jPanel2.add(jLabel65);
        jLabel65.setBounds(268, 312, 19, 24);

        jLabel66.setText("Tên");
        jPanel2.add(jLabel66);
        jLabel66.setBounds(30, 449, 19, 24);

        jLabel67.setText("Tên");
        jPanel2.add(jLabel67);
        jLabel67.setBounds(150, 449, 19, 24);

        jLabel68.setText("Tên");
        jPanel2.add(jLabel68);
        jLabel68.setBounds(268, 449, 19, 24);
        jPanel2.add(jLabel69);
        jLabel69.setBounds(385, 30, 0, 0);

        jLabel70.setText("role");
        jPanel2.add(jLabel70);
        jLabel70.setBounds(109, 180, 30, 16);

        jLabel71.setText("role");
        jPanel2.add(jLabel71);
        jLabel71.setBounds(225, 180, 30, 16);

        jLabel72.setText("role");
        jPanel2.add(jLabel72);
        jLabel72.setBounds(347, 180, 30, 16);

        jLabel73.setText("role");
        jPanel2.add(jLabel73);
        jLabel73.setBounds(347, 316, 30, 16);

        jLabel74.setText("role");
        jPanel2.add(jLabel74);
        jLabel74.setBounds(109, 316, 40, 16);

        jLabel75.setText("role");
        jPanel2.add(jLabel75);
        jLabel75.setBounds(229, 316, 30, 16);

        jLabel76.setText("role");
        jPanel2.add(jLabel76);
        jLabel76.setBounds(347, 453, 30, 16);

        jLabel77.setText("role");
        jPanel2.add(jLabel77);
        jLabel77.setBounds(109, 453, 30, 16);

        jLabel78.setText("role");
        jPanel2.add(jLabel78);
        jLabel78.setBounds(229, 453, 30, 16);

        jButton7.setText("Bắt Đầu");
        jPanel2.add(jButton7);
        jButton7.setBounds(670, 440, 165, 53);

        jButton8.setText("Chỉnh sửa role");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);
        jButton8.setBounds(410, 440, 138, 52);

        jLabel79.setText("Sói");
        jPanel2.add(jLabel79);
        jLabel79.setBounds(233, 7, 20, 16);

        jLabel80.setText("Dân làng");
        jPanel2.add(jLabel80);
        jLabel80.setBounds(303, 7, 47, 16);

        jLabel81.setText("Bảo vệ");
        jPanel2.add(jLabel81);
        jLabel81.setBounds(385, 7, 35, 16);

        jLabel82.setText("Tiên Tri");
        jPanel2.add(jLabel82);
        jLabel82.setBounds(498, 8, 38, 16);

        jLabel83.setText("Kẻ lây nhiễm");
        jPanel2.add(jLabel83);
        jLabel83.setBounds(577, 7, 68, 16);

        jLabel84.setText("Sói Tri");
        jPanel2.add(jLabel84);
        jLabel84.setBounds(233, 37, 50, 16);

        jLabel85.setText("Xạ thủ");
        jPanel2.add(jLabel85);
        jLabel85.setBounds(303, 37, 34, 16);

        jLabel86.setText("Thầy Đồng");
        jPanel2.add(jLabel86);
        jLabel86.setBounds(385, 37, 57, 16);

        jLabel87.setText("Thằng hề");
        jPanel2.add(jLabel87);
        jLabel87.setBounds(498, 37, 49, 16);

        jLabel88.setText("Role 10");
        jPanel2.add(jLabel88);
        jLabel88.setBounds(577, 37, 38, 16);

        jLabel89.setText("0");
        jLabel89.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel89);
        jLabel89.setBounds(209, 6, 18, 18);

        jLabel90.setText("0");
        jLabel90.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel90);
        jLabel90.setBounds(209, 36, 18, 18);

        jLabel91.setText("0");
        jLabel91.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel91);
        jLabel91.setBounds(279, 6, 18, 18);

        jLabel92.setText("0");
        jLabel92.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel92);
        jLabel92.setBounds(279, 36, 18, 18);

        jLabel93.setText("0");
        jLabel93.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel93);
        jLabel93.setBounds(363, 6, 18, 18);

        jLabel94.setText("0");
        jLabel94.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel94);
        jLabel94.setBounds(361, 36, 18, 18);

        jLabel95.setText("0");
        jLabel95.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel95);
        jLabel95.setBounds(479, 6, 18, 18);

        jLabel96.setText("0");
        jLabel96.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel96);
        jLabel96.setBounds(479, 36, 18, 18);

        jLabel97.setText("0");
        jLabel97.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel97);
        jLabel97.setBounds(553, 6, 18, 18);

        jLabel98.setText("0");
        jLabel98.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 1, true));
        jPanel2.add(jLabel98);
        jLabel98.setBounds(553, 36, 18, 18);

        jLabel99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/avatar_background_day.png"))); // NOI18N
        jLabel99.setText("jLabel99");
        jPanel2.add(jLabel99);
        jLabel99.setBounds(3, 350, 920, 170);

        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/emoji_sun.png"))); // NOI18N
        jPanel2.add(jLabel100);
        jLabel100.setBounds(720, -20, 403, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
